version: '3'
services:

  web:
    build: .
    container_name: web_container
    ports:
      - "8000:8000"
    command: > 
      bash -c "
      ls && 
      python3 manage.py makemigrations &&
      python3 manage.py makemigrations users &&
      python3 manage.py migrate && 
      python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
